apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-music
resources:
- namespace.yaml
- website-deploy.yaml
- website-ingress.yaml
- website-svc.yaml
images:
- digest: sha256:e12c976117ec1eb1aac18485dd0ff53136cd6330fdfb2ef9e71ae56e9c24265a
  name: docker.io/ralvares/spring-music
