apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- website-deploy.yaml
- website-ingress.yaml
- website-svc.yaml
images:
- digest: sha256:a5dd3112feec7aa57d39e80251850911480b72479db50cce9ec2b5ee52e307bf
  name: docker.io/ralvares/spring-music
