apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-music
resources:
- namespace.yaml
- website-deploy.yaml
- website-ingress.yaml
- website-svc.yaml
images:
- digest: sha256:13c697b55c990dfdea7800b0a8c44ce14a9372e600c89aaad5e8609a3c9e8df4
  name: docker.io/ralvares/spring-music
