apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- website-deploy.yaml
- website-ingress.yaml
- website-svc.yaml
images:
- digest: sha256:1691a9aac0eb33629303df84fb07323fcba726f2589df3db731bc57c5564c969
  name: docker.io/ralvares/spring-music
