apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-music
resources:
- namespace.yaml
- website-deploy.yaml
- website-ingress.yaml
- website-svc.yaml
images:
- digest: sha256:bb95f996a756a10de0a2c05ba163708e10b28762d8127d6dad5aa1bfc78326e4
  name: docker.io/ralvares/spring-music
