apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-music
resources:
- namespace.yaml
- website-deploy.yaml
- website-ingress.yaml
- website-svc.yaml
images:
- digest: sha256:a377d75a589d6733bc209ca6a4dff1561d5e95eefa51928e2a12e2bea4e34129
  name: docker.io/ralvares/spring-music
