
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: spring-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-music
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - name: spring-music
        image: docker.io/ralvares/spring-music@sha256:1691a9aac0eb33629303df84fb07323fcba726f2589df3db731bc57c5564c969
        ports:
        - containerPort: 8080

