apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-ingress
  labels:
    app: argocdrocks
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: argocdrocks.vcap.me
    http:
      paths:
      - backend:
          service:
            name: website-service
            port:
              number: 80
        path: /
        pathType: Prefix
