apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  labels:
    app: argocdrocks
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: argocdrocks.vcap.me
    http:
      paths:
      - backend:
          service:
            name: website-service
            port:
              number: 80
        path: /
        pathType: Prefix
